.ifndef __GRAPHICS_INC__
__GRAPHICS_INC__ = 1

.import gfx_modshrineTiles
.import gfx_modshrinePal
.import gfx_modshrineMap

.import gfx_ifontTiles

.import gfx_introlettersTiles

.import gfx_introbgTiles
.import gfx_introbgMap
.import gfx_introbgPal

.import gfx_splashTiles
.import gfx_splashPal
.import gfx_splashMap

.import gfx_titleMap
.import gfx_titlePal
.import gfx_titleTiles

.import gfx_player1Tiles
.import gfx_player1Pal

.import gfx_player2Tiles
.import gfx_player2Pal

.import gfx_player3Tiles
.import gfx_player3Pal

.import gfx_dongles1Tiles
.import gfx_dongles1Pal

DONGLE_SHADOW = 64
DONGLE_BOX = 68
DONGLE_KEY = 72
DONGLE_LOCK = 96
DONGLE_BUTTON = 74
DONGLE_BUTTONDOWN = 76
DONGLE_EXIT = 104
DONGLESPAL = 3

.import gfx_infobar_bgTiles
.import gfx_infobar_bgPal
.import gfx_infobar_bgMap

.import gfx_laserTiles
.import gfx_laserPal

.import gfx_sfontTiles
.import gfx_sfontPal

.import gfx_conveyorTiles

.import gfx_explosionTiles
.import gfx_explosionPal

.import gfx_starsTiles
.import gfx_starsPal
.import gfx_starsMap

.import gfx_baddieTiles
.import gfx_baddiePal

.import gfx_pwbracketPal
.import gfx_pwcharsPal
.import gfx_pwbracketTiles
.import gfx_pwcharsTiles

.import gfx_arnold1Tiles
.import gfx_arnold1Pal

.endif
