;-----------------------------------------------------------------------------
; this is table of default tempos, indexed by system number (aka speed)
;-----------------------------------------------------------------------------

defaultTempos
	.db		$26			; Main only @ 60Hz
	.db		$26			; Sub  only @ 60Hz
	.db		$26			; Both      @ 60Hz
	.db		$4d			; Both		@ 120Hz
	.db		$9b			; Both		@ 240Hz
	.db		$c3			; Both		@ 300Hz
	
